### ISSUE TITLE
C code generation broken after v2.85.5

### ISSUE THREAD

**Issue by Ebsz** [grame-cncm/faust#1260]
Hi,

After updating to v2.85.5 I found my previously working project no longer compiles due to linking errors with `faustmini`/`faustmaxi`.

The issue seems to stem from commit 42db599:

```C
// before
static inline int max_i(int a, int b) { return (a > b) ? a : b; }
// after
inline int faustmaxi(int a, int b) { return (a > b) ? a : b; }
```

## Steps to reproduce

1. Create the following files:

```Faust
// minimal.dsp
import("stdfaust.lib");

process = os.osc(234);
```

```C
// test.c
#include  <faust/gui/CInterface.h>
#include "dsp.h"

int main() {}
```
2. Generate C code with `faust --language c -o dsp.h test.dsp`

3. Compile with `gcc -lm test.c`. This yields the following error:

```
/usr/bin/ld: /tmp/cc0xhS7L.o: in function `computemydsp':
test.c:(.text+0x644): undefined reference to `faustmini'
/usr/bin/ld: test.c:(.text+0x650): undefined reference to `faustmaxi'
collect2: error: ld returned 1 exit status
```

## Context
- Faust 2.85.5
- Confirmed on GCC 15.2.1, as well as GCC 16.1.1
- Arch Linux

## Possible solution
Adding the `static` keyword to `faustmini`/`faustmaxi` in the generated `dsp.h` resolves the problem locally - so unless there was a particular reason it was removed in the first place, I assume it should be an easy fix?

**Comment by sletz** [comment]
Thanks for reporting, fixed in version 2.85.8 on master-dev branch.

**Comment by Ebsz** [comment]
Amazing, thank you for the quick response!
