### ISSUE TITLE
faust2 compile errors on Trusty (Ubuntu 14.04)

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#71]
Using the latest git sources of Faust2, I'm getting the following build errors on Ubuntu 14.04:

~~~
g++ -O3 -std=c++11 -Wall -Wuninitialized -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -Igenerator/interpreter -Igenerator/rust -DINSTALL_PREFIX='"/usr"' -std=gnu++11 -O1 -fPIC -D__USE_MINGW_ANSI_STDIO -Wall -Wuninitialized -fvisibility=hidden -Wno-overloaded-virtual -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -Igenerator/interpreter -Igenerator/rust -DINSTALL_PREFIX='"/usr"' -I`/usr/bin/llvm-config-3.5 --includedir` -I../architecture -DLLVM_35 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS  -DASMJS_BUILD -DC_BUILD -DCPP_BUILD -DFIR_BUILD -DINTERP_BUILD -DJAVA_BUILD -DJS_BUILD -DLLVM_BUILD -DRUST_BUILD -DWASM_BUILD   -c -o libcode.o libcode.cpp
In file included from generator/interpreter/interpreter_dsp_aux.hh:37:0,
                 from generator/interpreter/interpreter_code_container.hh:26,
                 from generator/interpreter/interpreter_code_container.cpp:26,
                 from libcode.cpp:79:
generator/interpreter/fir_interpreter.hh:502:13: warning: multi-line comment [-Wcomment]
             //#define dispatch_next() { (*it)->write(&std::cout); std::cout << "int_stack_index " << int_stack_index << " real_stack_index " << real_stack_index << std::endl; \
             ^
generator/interpreter/fir_interpreter.hh: In member function ‘void FIRInterpreter<T>::ExecuteBlock(FIRBlockInstruction<T>*)’:
generator/interpreter/fir_interpreter.hh:813:65: error: there are no arguments to ‘__builtin_sadd_overflow’ that depend on a template parameter, so a declaration of ‘__builtin_sadd_overflow’ must be available [-fpermissive]
                         if (__builtin_sadd_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:813:65: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
generator/interpreter/fir_interpreter.hh:837:65: error: there are no arguments to ‘__builtin_ssub_overflow’ that depend on a template parameter, so a declaration of ‘__builtin_ssub_overflow’ must be available [-fpermissive]
                         if (__builtin_ssub_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:861:65: error: there are no arguments to ‘__builtin_smul_overflow’ that depend on a template parameter, so a declaration of ‘__builtin_smul_overflow’ must be available [-fpermissive]
                         if (__builtin_smul_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh: In instantiation of ‘void FIRInterpreter<T>::ExecuteBlock(FIRBlockInstruction<T>*) [with T = double]’:
generator/interpreter/interpreter_dsp_aux.hh:768:13:   required from ‘void interpreter_dsp_aux<T>::instanceConstants(int) [with T = double]’
/usr/lib/llvm-3.5/include/llvm/IR/Instructions.h:152:7:   required from here
generator/interpreter/fir_interpreter.hh:813:65: error: ‘__builtin_sadd_overflow’ was not declared in this scope
                         if (__builtin_sadd_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:837:65: error: ‘__builtin_ssub_overflow’ was not declared in this scope
                         if (__builtin_ssub_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:861:65: error: ‘__builtin_smul_overflow’ was not declared in this scope
                         if (__builtin_smul_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh: In instantiation of ‘void FIRInterpreter<T>::ExecuteBlock(FIRBlockInstruction<T>*) [with T = float]’:
generator/interpreter/interpreter_dsp_aux.hh:768:13:   required from ‘void interpreter_dsp_aux<T>::instanceConstants(int) [with T = float]’
/usr/lib/llvm-3.5/include/llvm/IR/Instructions.h:152:7:   required from here
generator/interpreter/fir_interpreter.hh:813:65: error: ‘__builtin_sadd_overflow’ was not declared in this scope
                         if (__builtin_sadd_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:837:65: error: ‘__builtin_ssub_overflow’ was not declared in this scope
                         if (__builtin_ssub_overflow(v1, v2, &res)) {
                                                                 ^
generator/interpreter/fir_interpreter.hh:861:65: error: ‘__builtin_smul_overflow’ was not declared in this scope
                         if (__builtin_smul_overflow(v1, v2, &res)) {
                                                                 ^
~~~

The full buildlog is here: <https://launchpad.net/~dr-graef/+archive/ubuntu/pure-lang.trusty/+build/13138750/+files/buildlog_ubuntu-trusty-amd64.faust2_2.3.4+git20170724+8989-1_BUILDING.txt.gz>

The same source builds fine on both Ubuntu 16.04 and 17.04 (as well as on current Arch Linux). I *think* that the LLVM version should be the same (LLVM 3.5) in either case, but Trusty might well have an older version of gcc and C/C++ library. (My last known good build on Trusty was rev. eabc2b5a6 from 2017-06-02.)

Any clues? Looks like the conditional code there has been in there for more than a year, so I suspect that gcc is to blame here -- maybe a recent gcc update on Trusty broke it. We could try to add `-fpermissive` to the compiler options as suggested in the error message, but I'm not sure whether that might break other things.

**Comment by sletz** [comment]
Which gcc version are you using ? It seems like the **__builtin_smul_overflow**  kind of functions were introduced in gcc 5.5 : https://gcc.gnu.org/gcc-5/changes.html

**Comment by agraef** [comment]
It seems that gcc-4.8 is being used on Trusty (at least on Launchpad, as can be seen in the build log). So that might be the culprit. But then why did it build there just a month ago?

**Comment by sletz** [comment]
Because some more code was activated  recently (inside the INTERPRETER_TRACE flag). GCC 5.0 seems to be 2 years old, so what should we do?

**Comment by agraef** [comment]
Ok, that explains it. Well, I don't know what Debian stable uses, but Ubuntu 14.04 is an LTS release which is still being used by many people and won't go EOL before 2019, so I really think we should fix this. (I could also work around it on Ubuntu 14.04 by patching up the package, but if we have a fix then why not just deploy it upstream? That would benefit all users and packagers alike.)

Technically, probably the easiest thing to do is to check the gcc version and add the required declarations or header to the source code on gcc < 5 where needed. I can spin up Trusty in a VM later today and figure out something that works.

**Comment by agraef** [comment]
Hmm, it looks like those builtins aren't supported at all on older gcc versions. :( Are there some suitable replacements, or does that mean that we'll just have to disable the INTERPRETER_TRACE stuff on older systems?

**Comment by agraef** [comment]
I guess that the most immediate solution would be to edit the definition of `INTERPRETER_TRACE` at the beginning of fir_interpreter.hh as follows:

~~~c
// This only works for gcc 5+ right now.
#if __GNUC__ >= 5
#define INTERPRETER_TRACE       1
//#define FULL_INTERPRETER_TRACE  1
#endif
~~~

Let me give that a whirl on Trusty.

**Comment by agraef** [comment]
Ok, that did the trick, fix committed and pushed, packages are currently building on Launchpad. Thanks! :)
