### PR TITLE
static_cast to prevent gcc compilation error, fixes #38

### LINKED ISSUE #38: Problems compiling faust2 on linux
I'm having some problems compiling current faust2 branch on Linux.

For starters I have to add `--std=c++11` to CXXFLAGS, which I do with
`CXXFLAGS="-O3 -Wall -Wuninitialized --std=c++11" make`

Then a typo error comes up in `compiler/generator/llvm/llvm_dsp_aux.cpp`, here's my patch:
```diff --git a/compiler/generator/llvm/llvm_dsp_aux.cpp b/compiler/generator/llvm/llvm_dsp_aux
index c4e9075..b0c0914 100644
--- a/compiler/generator/llvm/llvm_dsp_aux.cpp
+++ b/compiler/generator/llvm/llvm_dsp_aux.cpp
@@ -420,7 +420,7 @@ void llvm_dsp_factory_aux::startLLVMLibrary()
 #endif
 #if (!defined(LLVM_35) && !defined(LLVM_36) && !defined(LLVM_37) && !defined(LLVM_38) && !d
         if (!llvm_start_multithreaded()) {
-            std::cerr << "llvm_start_multithreaded error...\n");
+            std::cerr << "llvm_start_multithreaded error...\n";
         }
 #endif
     }
```

Then I get 
```generator/llvm/llvm_dsp_aux.cpp: In member function ‘bool llvm_dsp_factory_aux::initJIT(std::string&)’:
generator/llvm/llvm_dsp_aux.cpp:682:82: error: operands to ?: have different types ‘std::string {aka std::basic_string<char>}’ and ‘llvm::StringRef’
         builder.setMCPU((cpu == "") ? llvm::sys::getHostCPUName() : StringRef(cpu));
                                                                                  ^
```

I'm using a fairly ancient version of Ubuntu as my build machine, and trying to compile with gcc. That would be the problem, I guess.

Is the master branch functionally equivalent to faust2, in respect of supported language features? Will faust2 become the new master branch at some point?

I am happy to either stick to master/faust1, or switch to faust2 and build on a more modern machine, unless I'm missing something and this should actually work.

### PR DESCRIPTION
**Pull request by pingdynasty**
See https://github.com/grame-cncm/faust/issues/38

### CODE REVIEW

**Comment by pingdynasty** [comment]
wow, that was quick! :+1:

**Comment by agraef** [comment]
This breaks compilation for me on Linux, using either LLVM 3.5 or 4.0 on Arch. Here's the error message I get:

~~~make
make[1]: Entering directory '/home/ag/Sources/github/faust2/compiler'
g++ -O3 -std=c++11 -Wall -Wuninitialized -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -Igenerator/interpreter -DINSTALL_PREFIX='"/usr/local"' -std=gnu++11 -O1 -fPIC -D__USE_MINGW_ANSI_STDIO -Wall -Wuninitialized -fvisibility=hidden -Wno-overloaded-virtual -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -Igenerator/interpreter -DINSTALL_PREFIX='"/usr/local"' -I`/usr/bin/llvm-config --includedir` -I../architecture -DLLVM_40 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS  -DASMJS_BUILD -DC_BUILD -DCPP_BUILD -DFIR_BUILD -DINTERP_BUILD -DJAVA_BUILD -DJS_BUILD -DLLVM_BUILD -DWASM_BUILD   -c -o generator/llvm/llvm_dsp_aux.o generator/llvm/llvm_dsp_aux.cpp
generator/llvm/llvm_dsp_aux.cpp: In member function ‘bool llvm_dsp_factory_aux::initJIT(std::__cxx11::string&)’:
generator/llvm/llvm_dsp_aux.cpp:754:37: error: operands to ?: have different types ‘llvm::StringRef’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
         builder.setMCPU((cpu == "") ? llvm::sys::getHostCPUName() : static_cast<std::basic_string<char>>(StringRef(cpu)));
                         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator/llvm/llvm_dsp_aux.cpp:754:37: note:   and each type can be converted to the other
make[1]: *** [<builtin>: generator/llvm/llvm_dsp_aux.o] Error 1
make[1]: Leaving directory '/home/ag/Sources/github/faust2/compiler'
make: *** [Makefile:44: all] Error 2
~~~

Reverting rev. e65b90aba9df016047a9dcdb7cebfa43f50016ad makes the source compile again, so this pull request clearly is the culprit here.

(The Travis build failed as well, but much earlier, that's apparently because of a missing LLVM dependency.)

@pingdynasty What Linux system are you using, and what's your LLVM version?

In any case this needs to be fixed so that it works with recent LLVM versions again. I suggest reverting this PR and give it another try which makes sure that it works on LLVM 3.5+. If necessary, you can use conditional compilation to make it work on other (i.e., your) LLVM version.

**Comment by pingdynasty** [comment]
oops, sorry! I'm currently using LLVM 3.3, on Ubuntu 14.04.

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/a01ce7bcb12f5b78dca01fb545a21343d93777fd

**Comment by agraef** [comment]
@sletz, thanks a bunch. :) Any idea why the Travis builds suddenly keep failing? The build logs say that llvm-3.8 couldn't be found. Maybe a recent update of the build environment, but I can't find any information on what LLVM version they're running now.

@pingdynasty, no problem, normally that's what the Travis builds are for. Just keep in mind next time that some of us may be running much newer systems than you do. ;-)
