### ISSUE TITLE
faust2max6 still not compiling

### ISSUE THREAD

**Issue by bassik** [grame-cncm/faust#414]
Hello,
I have followed the guide and installed the newest MAX SDK and then modified the faustpath script in Xcode to make it pointing to the folder where the sdk is but still not successful.
I still get the error related to ext.h.
I put the content of the SDK in my usr folder 

I am using OSX High Sierra on a mac mini 2018.

I am using a precompiled version of FAUST because I cannot compile one myself as I get errors related to make (bin/sh is not a command - error message).

Not sure what I am doing wrong here so I need to ask for help.
Thanks

**Comment by sletz** [comment]
Why no using the online compiler that you can access in Faust IDE ? https://faust.grame.fr/ide/
<img width="1200" alt="Capture d’écran 2020-03-09 à 12 54 02" src="https://user-images.githubusercontent.com/1430487/76210770-14b53580-6205-11ea-8ec2-bcc4288113dd.png">

**Comment by bassik** [comment]
Yes I can (thanks for the link) but I would like to be able to do that even if I am not online.

**Comment by bassik** [comment]
Hello,
I managed to get the compiler and faust2max6 working with the newest SDK 8.0.3 by copying the files in my document folder and then modify the faustpath script.

But now when I have an issue with the compiler that I do not understand, error below:

hoa_decoder_lebedev50_binaural.cpp:7547:17982: fatal error: bracket nesting level exceeded maximum of 512
hoa_decoder_lebedev50_binaural.cpp:7547:17982: note: use -fbracket-depth=N to increase maximum nesting level

Cannot find how to increase the nesting level on the manual neither the -fbracket-depth options.

**Comment by sletz** [comment]
You'll have to change -fbracket-depth in **faust2max** script.

**Comment by bassik** [comment]
Thanks!!! It worked!!!!
