### ISSUE TITLE
use of undeclared identifier 'IP_PKTINFO'

### ISSUE THREAD

**Issue by ryandesign** [grame-cncm/faust#129]
Hi, we have faust building successfully in MacPorts on OS X 10.7 and later, but on Mac OS X 10.6, we get this error:

```
ip/posix/UdpSocket.cpp:236:36: error: use of undeclared identifier 'IP_PKTINFO'
                setsockopt (socket_, IPPROTO_IP, IP_PKTINFO, &val, sizeof(val));
                                                 ^
ip/posix/UdpSocket.cpp:248:24: error: use of undeclared identifier 'IP_PKTINFO'
                                cmsg->cmsg_type != IP_PKTINFO)
                                                   ^
```

Here's a full [build log](https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/55258/steps/install-port/logs/stdio).

**Comment by sletz** [comment]
10.6 is too old I guess.

**Comment by ryandesign** [comment]
Too old to understand `IP_PKTINFO`, evidently. So I'm asking if the code can be rewritten to avoid `IP_PKTINFO`. faust (0.9.67) used to compile on 10.6.

**Comment by sletz** [comment]
The oscpack library we are using now is more recent. So I guess 10.6 is to be dropped.

**Comment by ryandesign** [comment]
I didn't realize the problem originated in an embedded copy of a separately developed library. I'll be happy to report the bug to the developers of oscpack, if you happen to know where I can do that. I only found the [original developer's web page](http://www.rossbencina.com/code/oscpack), but he appears to have abandoned the software.

It looks like FreeBSD has [created a patch for this problem](https://svnweb.freebsd.org/ports/head/audio/faust/files/patch-architecture_osclib_oscpack_ip_posix_UdpSocket.cpp?view=markup&pathrev=456858); maybe that could be incorporated in the mean time.

**Comment by sletz** [comment]
Using the FreeBSD patch is probably the way to go, possibly giving it back to Ross Bencina ?

**Comment by agraef** [comment]
> Using the FreeBSD patch is probably the way to go, possibly giving it back to Ross Bencina ?

But the oscpack sources are included in Faust, so fixing it there should get rid of the issue, no?

**Comment by ryandesign** [comment]
> Using the FreeBSD patch is probably the way to go, possibly giving it back to Ross Bencina ?

Ross's web site links to a Google Code project that hasn't been updated since 2013 and doesn't use `IP_PKTINFO`. So I don't know where your updated version of oscpack comes from, but it doesn't appear to be from there.

**Comment by sletz** [comment]
@dfober : do you remember when and why this oscpack change happened ? Should we simply apply the FreeBSD patch?

**Comment by agraef** [comment]
@sletz: rev. 280344fad69afb9167f24167a3c747842fa62dea. That's by you. :)

**Comment by agraef** [comment]
Clearly, `IP_PKTINFO` is supported on Linux, but I'm not convinced that's it in POSIX, otherwise the Mac should have it. Same goes for Windows.

**Comment by sletz** [comment]
Yes, but I think I copied a piece of code that @dfober gave me, by do not remember from where... 
(well the why is probably this `allowBroadcast` new function...)

**Comment by agraef** [comment]
Unfortunately, the BSD patch doesn't really solve the problem, it only works around the problem by #ifdefing out some code that looks rather crucial to me.

IIRC, that commit implements osclib's capability to listen on broadcast addresses and then reply to the actual sender of whoever sends an OSC message first. (@dfober should know this better.) Which isn't essential, but I found this pretty useful when I played around with it.

**Comment by agraef** [comment]
There's probably some way to do that without requiring non-POSIX.1 stuff, it's just a matter of finding out how. I'm no networks specialist, but @dfober is an expert on everything OSC, hopefully he should be able to figure that out. :)

**Comment by agraef** [comment]
Then again, the BSD patch might be ok as a solution for legacy systems -- time will resolve that issue anyway.

**Comment by dfober** [comment]
> Le 4 févr. 2018 à 09:59, Stéphane Letz <notifications@github.com> a écrit :
> 
> Yes, but I think I copied a piece of code that @dfober <https://github.com/dfober> gave me, by do not remember from where...
> (well the why is probably this allowBroadcast new function...)
> 

right, I’ve made some changes to the original library,
anyway, I’ll have a look at the latest one and see how I can merge

**Comment by agraef** [comment]
This is somewhat off-topic, but while we're at it: I think that the root of all evil here is that each Faust module needs its own UDP port for incoming OSC. Which can't really be avoided for Faust modules running as stand-alone, self-contained processes.

I think that a better solution would be to have a dedicated Faust-OSC daemon running on each system or for each user session, which is implemented as an OSC server sitting at a predictable address. This can be done in user space and osclib could have a call to launch that server if it isn't running already, to avoid the complexities and cross-platform issues of a system service. This OSC server would then manage *all* the Faust-OSC traffic for that session and dispatch OSC using a module prefix to all the OSC addresses. One might also throw in Zeroconf (Avahi/Bonjour) support for good measure to make this even easier. (That's pretty much what I'm doing in Pd right now, but this case is of course much less complicated because all Faust modules live in a single process there.)

Of course the downside of such an approach is added latency, but since the OSC server would dispatch to locally running Faust modules only, the overhead should be tolerable, and IMHO this would make things so much easier for Faust users, that it's worth the effort. And it won't waste precious UDP ports.

That's maybe something that we should talk about during the upcoming IFC at JGU. @dfober will you be there?

**Comment by agraef** [comment]
BTW, for the record, the official source of oscpack now seems to be on github (last updated 2014): https://github.com/RossBencina/oscpack

There are a few forks of this, but they're all about the same as Ross' version (give or take 1-2 commits), except this one which apparently started separately as a clone of the GoogleCode repo (last updated 2015): https://github.com/MariadeAnton/oscpack

**Comment by dfober** [comment]
> Le 4 févr. 2018 à 10:31, Albert Graef <notifications@github.com> a écrit :
> 
> This is somewhat off-topic, but while we're at it: I think that the root of all evil here is that each Faust module needs its own UDP port for incoming OSC. Which can't really be avoided for Faust modules running as stand-alone, self-contained processes.
> 
> I think that a better solution would be to have a dedicated Faust-OSC daemon running on each system or for each user session, which is implemented as an OSC server sitting at a predictable address. This can be done in user space and osclib could have a call to launch that server if it isn't running already, to avoid the complexities and cross-platform issues of a system service. This OSC server would then manage all the Faust-OSC traffic for that session and dispatch OSC using a module prefix to all the OSC addresses. One might also throw in Zeroconf (Avahi/Bonjour) support for good measure to make this even easier. (That's pretty much what I'm doing in Pd right now, but this case is of course much less complicated because all Faust modules live in a single process there.)
> 
> Of course the downside of such an approach is added latency, but since the OSC server would dispatch to locally running Faust modules only, the overhead should be tolerable, and IMHO this would make things so much easier for Faust users, that it's worth the effort. And it won't waste precious UDP ports.
> 
> That's maybe something that we should talk about during the upcoming IFC at JGU. @dfober <https://github.com/dfober> will you be there?
> 
yes, I’ll be there.
